apiVersion: poison.venom.gule-gulzar.com/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: venom
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  # TODO(user): Add fields here
