apiVersion: poison.venom.gule-gulzar.com/v1
kind: ClusterScan
metadata:
  name: clusterscan-sample
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: testjob
          restartPolicy: Never
