apiVersion: poison.venom.gule-gulzar.com/v1
kind: ClusterScan
metadata:
  name: clusterscan-one-off
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: testjob
          restartPolicy: Never

--- 

apiVersion: poison.venom.gule-gulzar.com/v1
kind: ClusterScan
metadata:
  name: clusterscan-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: testjob
          restartPolicy: Never
  jobRetentionTime: 5
